name: Deploy to Steam Workshop

on:
  workflow_call:
    inputs:
      steam_config_path:
        description: "Путь к конфигу Steam Workshop для данного мода"
        required: true
        type: string
      lint_workflow_file:
        description: "Имя файла lint workflow"
        required: false
        type: string
        default: "lint_es_mod.yml"
      branch:
        description: "Ветка для проверки статуса lint workflow"
        required: false
        type: string
        default: "main"
    secrets:
      STEAM_SHARED_SECRET:
        description: "Steam Shared Secret"
        required: true
      STEAM_USERNAME:
        description: "Steam Username"
        required: true
      STEAM_PASSWORD:
        description: "Steam Password"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout scripts
        uses: actions/checkout@v3
        with:
          repository: zImpact/es_mod_workflow
          path: scripts
          sparse-checkout: |
            check_lint_status.sh
            deploy_to_steam.sh

      - name: Check lint status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x ./scripts/check_lint_status.sh
          ./scripts/check_lint_status.sh "${{ inputs.lint_workflow_file }}" "${{ inputs.branch }}" "basic-lint"

      - name: Install SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Generate Steam Guard 2FA code
        id: steam-2fa
        uses: CyberAndrii/steam-totp@v1
        with:
          shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}

      - name: Deploy to Steam Workshop
        run: |
          chmod +x ./scripts/deploy_to_steam.sh
          ./scripts/deploy_to_steam.sh "${{ secrets.STEAM_USERNAME }}" "${{ secrets.STEAM_PASSWORD }}" "${{ steps.steam-2fa.outputs.code }}" "${{ inputs.steam_config_path }}"