name: Download tools

on:
  workflow_call:
    inputs:
      sdk_version:
        description: "Версия Ren'Py SDK"
        required: true
        type: string
        default: "8.1.3"
      google_drive_id:
        description: "ID Google Drive архива с Бесконечным летом"
        required: true
        type: string
        default: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
      es_ver:
        description: "Версия архива Бесконечного лета для кэширования"
        required: true
        type: string
        default: "1"

jobs:
  download-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Set up cache for Ren'Py SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: "~/.renpy-sdk"
          key: ${{ runner.os }}-renpy-sdk-${{ inputs.sdk_version }}

      - name: Download Ren'Py SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.renpy-sdk
          wget -q "https://www.renpy.org/dl/${{ inputs.sdk_version }}/renpy-${{ inputs.sdk_version }}-sdk.tar.bz2"
          tar -xjf "renpy-${{ inputs.sdk_version }}-sdk.tar.bz2" -C ~/.renpy-sdk
          rm "renpy-${{ inputs.sdk_version }}-sdk.tar.bz2"

      - name: Set up cache for Everlasting Summer game files
        id: cache-game
        uses: actions/cache@v3
        with:
          path: "./game_files"
          key: ${{ runner.os }}-everlasting-summer-${{ inputs.es_ver }}-${{ inputs.google_drive_id }}

      - name: Download Everlasting Summer
        if: steps.cache-game.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./game_files
          pip install gdown
          gdown --id "${{ inputs.google_drive_id }}" -O "Everlasting Summer.zip"
          unzip -q "Everlasting Summer.zip" -d "./game_files"
          rm "Everlasting Summer.zip"