name: ES Mod

on:
  workflow_call:
    inputs:
      project_name:
        description: "Название мода"
        required: true
        type: string
      sdk_version:
        description: "Версия Ren'Py SDK"
        required: true
        type: string
        default: "8.1.3"
      google_drive_id:
        description: "ID Google Drive архива с Бесконечным летом"
        required: true
        type: string
        default: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
      es_ver:
        description: "Версия архива Бесконечного лета для кэширования"
        required: true
        type: string
        default: "7"
      grammar_check_files:
        description: "Список файлов для проверки орфографии, разделённых пробелами"
        required: false
        type: string
        default: ""
      exclusions:
        description: "Файл с командами/словами исключениями"
        required: false
        type: string
        default: ""
      output_type:
        description: "Формат вывода"
        required: false
        type: string
        default: ""
      folder:
        description: "Папка для проверки на маркеры"
        required: false
        type: string
        default: ""
      markers:
        description: "Путь к файлу маркеров"
        required: false
        type: string
        default: ""
      steam_workshop_config_path:
        description: "Путь к конфигу Steam Workshop"
        required: true
        type: string

  workflow_dispatch:

env:
  SDK_VERSION: "${{ inputs.sdk_version }}"
  GOOGLE_DRIVE_ID: "${{ inputs.google_drive_id }}"
  ES_VER: "${{ inputs.es_ver }}"
  PROJECT_NAME: "${{ inputs.project_name }}"
  GRAMMAR_CHECK_FILES: "${{ inputs.grammar_check_files }}"
  EXCLUSIONS: "${{ inputs.exclusions }}"
  OUTPUT_TYPE: "${{ inputs.output_type }}"
  FOLDER: "${{ inputs.folder }}"
  MARKERS: "${{ inputs.markers }}"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache for SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: "~/.renpy-sdk"
          key: ${{ runner.os }}-renpy-sdk-${{ env.SDK_VERSION }}

      - name: Download Ren'Py SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.renpy-sdk
          wget -q "https://www.renpy.org/dl/${{ env.SDK_VERSION }}/renpy-${{ env.SDK_VERSION }}-sdk.tar.bz2"
          tar -xjf "renpy-${{ env.SDK_VERSION }}-sdk.tar.bz2" -C ~/.renpy-sdk
          rm "renpy-${{ env.SDK_VERSION }}-sdk.tar.bz2"

      - name: Set up cache for Game
        id: cache-game
        uses: actions/cache@v3
        with:
          path: "./game_files"
          key: ${{ runner.os }}-everlasting-summer-${{ env.ES_VER }}-${{ env.GOOGLE_DRIVE_ID }}

      - name: Download Everlasting Summer
        if: steps.cache-game.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./game_files
          pip install gdown
          gdown --id "${{ env.GOOGLE_DRIVE_ID }}" -O "Everlasting Summer.zip"
          unzip -q "Everlasting Summer.zip" -d "./game_files"
          rm "Everlasting Summer.zip"

  marker-lint:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Marker Linter
        uses: zImpact/renpy_marker_linter@v1.0.2
        with:
          folder: "${{ env.FOLDER }}"
          markers: "${{ env.MARKERS }}"

  text-lint:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Text Linter
        uses: zImpact/renpy_text_linter@v1.0.10
        with:
          files: "${{ env.GRAMMAR_CHECK_FILES }}"
          exclusions: "${{ env.EXCLUSIONS }}"
          output_type: "${{ env.OUTPUT_TYPE }}"

  basic-lint:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache for SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: "~/.renpy-sdk"
          key: ${{ runner.os }}-renpy-sdk-${{ env.SDK_VERSION }}

      - name: Set up cache for Game
        id: cache-game
        uses: actions/cache@v3
        with:
          path: "./game_files"
          key: ${{ runner.os }}-everlasting-summer-${{ env.ES_VER }}-${{ env.GOOGLE_DRIVE_ID }}

      - name: Copy mod files to game directory
        run: |
          mkdir -p "./game_files/Everlasting Summer/game/${{ env.PROJECT_NAME }}"
          cp -r ./code ./images ./sounds "./game_files/Everlasting Summer/game/${{ env.PROJECT_NAME }}"
          echo "Folder contents:"
          ls "./game_files/Everlasting Summer/game"

      - name: Run Ren'Py Lint
        run: |
          ~/.renpy-sdk/renpy-${{ env.SDK_VERSION }}-sdk/renpy.sh "./game_files/Everlasting Summer/game/" lint lint_report.txt
        shell: bash

      - name: Display Lint Report
        run: |
          echo "### Отчет шага Basic Lint" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat lint_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  steam-workshop-deploy:
    needs: basic-lint
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SteamCMD and jq
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y steamcmd jq

      - name: Generate Steam Guard 2FA code
        id: steam-2fa
        uses: CyberAndrii/steam-totp@v1
        with:
          shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}

      - name: Deploy to Steam Workshop
        run: ./deploy_to_steam.sh "${{ secrets.STEAM_USERNAME }}" "${{ secrets.STEAM_PASSWORD }}" "${{ steps.steam-2fa.outputs.code }}" "${{ inputs.steam_workshop_config_path }}"