name: Lint ES Mod

on:
  workflow_call:
    inputs:
      project_name:
        description: "Название мода"
        required: true
        type: string
      sdk_version:
        description: "Версия Ren'Py SDK"
        required: true
        type: string
        default: "8.1.3"
      google_drive_id:
        description: "ID Google Drive архива с Бесконечным летом"
        required: true
        type: string
        default: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
      es_ver:
        description: "Версия архива Бесконечного лета для кэширования"
        required: true
        type: string
        default: "1"
      grammar_check_files:
        description: "Список файлов для проверки орфографии, разделённых пробелами (так же можно передать название папки)"
        required: false
        type: string
        default: ""
      exclusions:
        description: "Файл с командами/словами исключениями"
        required: false
        type: string
      output_type:
        description: "Формат вывода"
        required: false
        type: string
      folder:
        description: "Папка для проверки на маркеры"
        required: false
        type: string
      markers:
        description: "Путь к файлу маркеров"
        required: false
        type: string
      run_marker_lint:
        description: "Запуск marker-lint"
        required: false
        type: boolean
        default: true
      run_text_lint:
        description: "Запуск text-lint"
        required: false
        type: boolean
        default: true
      run_basic_lint:
        description: "Запуск basic-lint"
        required: false
        type: boolean
        default: true
      run_code_lint:
        description: "Запуск code-lint"
        required: false
        type: boolean
        default: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache for SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: "~/.renpy-sdk"
          key: ${{ runner.os }}-renpy-sdk-${{ inputs.sdk_version }}

      - name: Download Ren'Py SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.renpy-sdk
          wget -q "https://www.renpy.org/dl/${{ inputs.sdk_version }}/renpy-${{ inputs.sdk_version }}-sdk.tar.bz2"
          tar -xjf "renpy-${{ inputs.sdk_version }}-sdk.tar.bz2" -C ~/.renpy-sdk
          rm "renpy-${{ inputs.sdk_version }}-sdk.tar.bz2"

      - name: Set up cache for Game
        id: cache-game
        uses: actions/cache@v3
        with:
          path: "./game_files"
          key: ${{ runner.os }}-everlasting-summer-${{ inputs.es_ver }}-${{ inputs.google_drive_id }}

      - name: Download Everlasting Summer
        if: steps.cache-game.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./game_files
          pip install gdown
          gdown --id "${{ inputs.google_drive_id }}" -O "Everlasting Summer.zip"
          unzip -q "Everlasting Summer.zip" -d "./game_files"
          rm "Everlasting Summer.zip"

  marker-lint:
    if: ${{ inputs.run_marker_lint }}
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Marker Linter
        uses: zImpact/renpy_marker_linter@v1.0.2
        with:
          folder: "${{ inputs.folder }}"
          markers: "${{ inputs.markers }}"

  text-lint:
    if: ${{ inputs.run_text_lint }}
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Text Linter
        uses: zImpact/renpy_text_linter@v1.0.11
        with:
          files: "${{ inputs.grammar_check_files }}"
          exclusions: "${{ inputs.exclusions }}"
          output_type: "${{ inputs.output_type }}"

  basic-lint:
    if: ${{ inputs.run_basic_lint }}
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache for SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: "~/.renpy-sdk"
          key: ${{ runner.os }}-renpy-sdk-${{ inputs.sdk_version }}

      - name: Set up cache for Game
        id: cache-game
        uses: actions/cache@v3
        with:
          path: "./game_files"
          key: ${{ runner.os }}-everlasting-summer-${{ inputs.es_ver }}-${{ inputs.google_drive_id }}

      - name: Copy mod files to game directory
        run: |
          mkdir -p "./game_files/Everlasting Summer/game/${{ inputs.project_name }}"
          rsync -av --exclude='game_files' --exclude='.git' . "./game_files/Everlasting Summer/game/${{ inputs.project_name }}"
          echo "Folder contents:"
          ls "./game_files/Everlasting Summer/game"

      - name: Run Ren'Py Lint
        run: |
          ~/.renpy-sdk/renpy-${{ inputs.sdk_version }}-sdk/renpy.sh "./game_files/Everlasting Summer/game/" lint lint_report.txt
        shell: bash

      - name: Display Lint Report
        run: |
          echo "### Отчет шага Basic Lint" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat lint_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  code-lint:
    if: ${{ inputs.run_code_lint }}
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Code Linter
        uses: zImpact/renpy_code_linter@v1.0.0
        with:
          folder: "${{ inputs.folder }}"
          output_type: "${{ inputs.output_type }}"