name: Lint workflow

on:
  push:
    branches:
      - main

jobs:
  download-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Install actionlint
        run: |
          bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) latest /usr/local/bin
  
  lint-actionlint:
    runs-on: ubuntu-latest
    needs: download-tools
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run actionlint
        run: make lint-actionlint
  
  lint-yamllint:
    runs-on: ubuntu-latest
    needs: download-tools
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run yamllint
        run: make lint-yamllint
